seed: 2
output_path: "plots/"
plot_name: "V4prep05_1_maxdev3_msdeCURTAINS_desamble_fake"
contamination_style: "mean_std"
evaluate_the_worst_cases: False
do_plotting_in_contamination_evaluation: False
# parametetrs for cs_eval
CSEconf: "config/cs_eval/maxdev3_msde.yaml"

xlabel: "max deviation"

counts_windows_boot_load: "char/one_run_experiments/k50MB2048_1iret0con0W3000_3100_w0.5s1Nboot/binnedW100s16ei30004600fake/"
title: "$n=0.5,\\sigma=1$, maxdev3_msde CURTAINS desamble fake"
density: 0

ensambling_num: desamble
ensambling_type: mean