seed: 2
output_path: "plots/"
plot_name: "V4prep05_1_maxdev3_msdeCURTAINS_1mean"
contamination_style: "mean_std"
evaluate_the_worst_cases: False
do_plotting_in_contamination_evaluation: False
# parametetrs for cs_eval
CSEconf: "config/cs_eval/maxdev3_msde.yaml"

xlabel: "max deviation"

counts_windows_boot_load: "char/v4/k50MB2048_1iret0con0W3000_3100_w0.5s1Nboot/binnedW100s16ei30004600boot/"
title: "$n=0.5,\\sigma=1$, maxdev3_msde CURTAINS ensamble 1 mean"
density: 0

ensambling_num: 1
ensambling_type: mean
#Different contaminatations (vertical lines on the plot)
contaminations:
  - 0.01
  - 0.005
  - 0.0025
  - 0.002
  - 0.001
  - 0.009
  - 0.008
cont_paths:
  - "char/v4/k50MB2048_1iret0con0.1W3000_3100_w0.5s1Nrest/binnedW100s16ei30004600/"
  - "char/v4/k50MB2048_1iret0con0.05W3000_3100_w0.5s1Nrest/binnedW100s16ei30004600/"
  - "char/v4/k50MB2048_1iret0con0.025W3000_3100_w0.5s1Nrest/binnedW100s16ei30004600/"
  - "char/v4/k50MB2048_1iret0con0.02W3000_3100_w0.5s1Nrest/binnedW100s16ei30004600/"
  - "char/v4/k50MB2048_1iret0con0.01W3000_3100_w0.5s1Nrest/binnedW100s16ei30004600/"
  - "char/v4/k50MB2048_1iret0con0.009W3000_3100_w0.5s1Nrest/binnedW100s16ei30004600/"
  - "char/v4/k50MB2048_1iret0con0.008W3000_3100_w0.5s1Nrest/binnedW100s16ei30004600/"
colors:
  - "red"
  - "orange"
  - "gold"
  - "lime"
  - "green"
  - "cyan"
  - "steelblue"
postfix:
  - "MB"
  - "MB"
  - "MB"
  - "MB"
  - "MB"
  - "MB"
  - "MB"