seed: 2
output_path: "plots/"
plot_name: "V4prep05_1_maxdev5CURTAINS_desamble"
contamination_style: "mean_std"
evaluate_the_worst_cases: True
do_plotting_in_contamination_evaluation: False
# parametetrs for cs_eval
CSEconf: "config/cs_eval/maxdev5.yaml"

xlabel: "$\\tilde{\\chi}^2/n_{dof}$"

counts_windows_boot_load: "char/v4/k50MB2048_1iret0con0W3000_3100_w0.5s1Nboot/binnedW100s16ei30004600boot/"
title: "$n=0.5,\\sigma=1$, maxdev5 CURTAINS desamble"
density: 0

ensambling_num: desamble
ensambling_type: mean
#Different contaminatations (vertical lines on the plot)