seed: 2
output_path: "plots/"
plot_name: "V4prep05_1_maxdev3CURTAINS_0002"
contamination_style: "Uall"
evaluate_the_worst_cases: False
do_plotting_in_contamination_evaluation: False
# parametetrs for cs_eval
CSEconf: "config/cs_eval/maxdev3.yaml"

xlabel: "$\\tilde{\\chi}^2/n_{dof}$"

counts_windows_boot_load: "char/v4/k50MB2048_1iret0con0W3000_3100_w0.5s1Nboot/binnedW100s16ei30004600boot/"
title: "$n=0.5,\\sigma=1$, maxdev3 CURTAINS"
density: 0
#Different contaminatations (vertical lines on the plot)
contaminations:
  - 0.002
old_CS:
  - 0
cont_paths:
  - "char/v4/k50MB2048_1iret0con0.02W3000_3100_w0.5s1Nrest/binnedW100s16ei30004600/"
colors:
  - "lime"
postfix:
  - "MB"