seed: 1
output_path: "plots/"
plot_name: "V4prep05_1_maxdev3_msdersCURTAINS_15mean"
contamination_style: "median_quartiles"
evaluate_the_worst_cases: False
do_plotting_in_contamination_evaluation: False
# parametetrs for cs_eval
CSEconf: "config/cs_eval/maxdev3_msders.yaml"

xlabel: "MLS"

counts_windows_boot_load: "/home/users/o/oleksiyu/scratch/CS/response/k50MB2048_20iret0con0W3450_3550_w0.5s1Nboot/binnedW100s16ei30004600/"
title: ""
density: 0

ensambling_num: 15
ensambling_type: mean
labelling: "Z"