# Location of the data
# Algorithm requires files with all mJJ and images of the events 
# sorted in increasing order of mJJ for both training and evaluation
# "mjj_bkg_sort.npy"
# "mjj_sig_sort.npy"
#
#
verbose: False

# Some general properties of the datasets provided
jet_per_event: 2
image_size: 40
image_w: 40
image_h: 40

#Either specifie an ID if a single trainng is required
ID: 0
#OR
#Enable batched bootstrap training and evaluation for a range of ID's
restart: False
bootstrap: False
resample_signal: False

#Parameters of the training
memory_intensive: True
train_interval:
  - 3000
  - 3100
signal_fraction: 0 #THIS IS THE SIGNAL FRACTION OF THE SIGNAL DATASET TO USE DURING TRAINING
k: 50 #number of clusters to train
reproc_arg_string: "w 0.5 s 1 N"
MiniBatch: False #recommended to enable when doing bootstrapping
n_init: 1
batch_size: 2048

#Parameters for binning
W: 100 #Bin width 
steps: 16 #Number of bins
eval_interval: #Histogram window
  - 3000
  - 4600
separate_binning: False

#Retraining option not yet implemented - requires binning to be specified
retrain: 0