seed: 1
output_path: "plots/"
plot_name: "V4prep05_1_maxdev3_msdersCURTAINS_1mean"
contamination_style: "median_quartiles"
evaluate_the_worst_cases: False
do_plotting_in_contamination_evaluation: False
# parametetrs for cs_eval
CSEconf: "config/cs_eval/maxdev3_msders.yaml"

xlabel: "MLS"

counts_windows_boot_load: "char/v4/k50MB2048_1iret0con0W3000_3100_w0.5s1Nboot/binnedW100s16ei30004600/"
title: ""
density: 0

ensambling_num: 1
ensambling_type: mean
labelling: "Z"