seed: 2
output_path: "plots/compare/"
plot_name: "prep05_1_maxdev5_0005-1-10i"
contamination_style: "Umean_std_meanstd"
# parametetrs for cs_eval
CSEconf: "config/cs_eval/maxdev5.yaml"

xlabel: "$\\tilde{\\chi}^2/n_{dof}$"

counts_windows_boot_load: "char/v2/k50Trueret0con0W2600_2700_w0.5s1Nboot/binnedW100s200ei26006000boot/"
title: "$n=0.5,\\sigma=1$, maxdev5 CURTAINS"
density: 1
#Different contaminatations (vertical lines on the plot)
contaminations:
  - 0.005
  - 0.005
  - 0.005
  - 0.005
old_CS:
  - 1
  - 0
  - 0
  - 0
cont_paths:
  - "char/old_char/BS26w60wk50ret0con0.05W100ste200rewsqrtsme1ID10/"
  - "char/v2/k50Trueret0con0.05W2600_2700_w0.5s1Nrest/binnedW100s200ei26006000/"
  - "char/v2/k50True10ret0con0.05W2600_2700_w0.5s1Nrest/binnedW100s200ei26006000/"
  - "char/v2/k50True50ret0con0.05W2600_2700_w0.5s1Nrest/binnedW100s200ei26006000/"
colors:
  - "red"
  - "orange"
  - "green"
  - "blue"
postfix:
  - "old class"
  - "MB"
  - "MB10i"
  - "MB50i"
