seed: 2
output_path: "plots/compare/"
plot_name: "old_to_new05_1_maxdev5_all"
contamination_style: "Uall"

CSEconf: "config/cs_eval/maxdev5.yaml"

xlabel: "$\\tilde{\\chi}^2/n_{dof}$"

counts_windows_boot_load: 
  - "char/v2/k50Trueret0con0W2600_2700_w0.5s1Nboot/binnedW100s200ei26006000boot/"
  - "old05_1"
title: "$n=0.5,\\sigma=1$, method 1"
density: 1

#Different contaminatations (vertical lines on the plot)
contaminations:
  - 0.01
  - 0.005
  - 0.0025
  - 0.01
  - 0.005
  - 0.0025
old_CS:
  - 1
  - 1
  - 1
  - 0
  - 0
  - 0
cont_paths:
  - "char/old_char/BS26w60wk50ret0con0.1W100ste200rewsqrtsme1ID10/" 
  - "char/old_char/BS26w60wk50ret0con0.05W100ste200rewsqrtsme1ID10/" 
  - "char/old_char/BS26w60wk50ret0con0.025W100ste200rewsqrtsme1ID10/"
  - "char/v2/k50Trueret0con0.1W2600_2700_w0.5s1Nrest/binnedW100s200ei26006000/"
  - "char/v2/k50Trueret0con0.05W2600_2700_w0.5s1Nrest/binnedW100s200ei26006000/"
  - "char/v2/k50Trueret0con0.025W2600_2700_w0.5s1Nrest/binnedW100s200ei26006000/"
colors:
  - "red"
  - "orange"
  - "gold"
  - "darkgreen"
  - "green"
  - "lime"
postfix:
  - ""
  - ""
  - ""
  - ""
  - ""
  - ""