seed: 2
output_path: "plots2/"
plot_name: "prep05_1_LABmaxdev5_max-maxnorm-dev"

labeling: ">5sigma"   # "kmeans_der" #"kmeans_der"#">5sigma"#
filterr: "med"
test_statistic: "max-maxnorm-dev"
xlabel: "max-maxnorm-dev"

counts_windows_boot_load: "old05_1"
title: "$n=0.5,\\sigma=1$, method 1"

#Different contaminatations (vertical lines on the plot)
contaminations:
  - 0.01
  - 0.005
  - 0.0025
  - 0.01
  - 0.005
  - 0.0025
old_CS:
  - True
  - True
  - True
  - False
  - False
  - False
cont_paths:
  - "char/old_char/BS26w60wk50ret0con0.1W100ste200rewsqrtsme1ID10/" 
  - "char/old_char/BS26w60wk50ret0con0.05W100ste200rewsqrtsme1ID10/" 
  - "char/old_char/BS26w60wk50ret0con0.025W100ste200rewsqrtsme1ID10/"
  - "config/s0.1_0.5_1_MB.yml"
  - "config/s0.05_0.5_1_MB.yml"
  - "config/s0.025_0.5_1_MB.yml"
colors:
  - "red"
  - "orange"
  - "gold"
  - "darkgreen"
  - "green"
  - "lime"
postfix:
  - ""
  - ""
  - ""
  - "MB"
  - "MB"
  - "MB"