seed: 2
output_path: "plots/"
plot_name: "prep05_1_maxdev5CURTAINS_0005"
contamination_style: "Uall"
# parametetrs for cs_eval
CSEconf: "config/cs_eval/maxdev5.yaml"

xlabel: "$\\tilde{\\chi}^2/n_{dof}$"

counts_windows_boot_load: "char/v2/k50Trueret0con0W2600_2700_w0.5s1Nboot/binnedW100s16ei30004600boot/"
title: "$n=0.5,\\sigma=1$, maxdev5 CURTAINS"
density: 1
#Different contaminatations (vertical lines on the plot)
contaminations:
  - 0.005
old_CS:
  - 0
cont_paths:
  - "char/v2/k50Trueret0con0.05W2600_2700_w0.5s1Nrest/binnedW100s16ei30004600/"
colors:
  - "orange"
postfix:
  - "MB"
