
#overal run options
verbous: False 
plotting: False
save: False
save_path: "cs_performance_evaluation/"

# specify test statistic to compute:
labeling: "2meansder"   
filterr: "med"
steal_sd_anomalypoor: 2

#random seed
sid: 0

test_statistic: "chisq_ndof"
